# format based on example in quickstart section at https://docs.python.org/3/library/configparser.html

[database.local]
Port = 5439
Host = 127.0.0.1
DatabaseName = measurements

[database.cloud]
Port = 5432
Host = aqrc-ascent-psqlsvr-w2.postgres.database.azure.com
DatabaseName = measurements

[data.storage]
WriteLocalDatabase = on

[file.storage]
ProcessingBasePath = processing
ProcessingFinishedBasePath = archive
LogsPath = logs

[site.info]
SiteNumber = 99
SiteName = Dev Test Site
SiteCode = Test

[xact]
Enabled = False
InstrumentDataFolder = test_data/xact/instrument
ArchiveDataFolder = test_data/xact/archive

[smps]
Enabled = True
InstrumentDataFolder = test_data/smps/instrument
ArchiveDataFolder = test_data/smps/archive

[acsm]
Enabled = False
InstrumentDataFolder = test_data/acsm/instrument
ArchiveDataFolder = test_data/acsm/archive

[ae33]
Enabled = False
IgnoreFolders = True

[dryerstats]
Enabled = True
InstrumentDatafolder = test_data/dryerstats/instrument
ArchiveDataFolder = test_data/dryerstats/archive