-- Load data for ASCENT sites
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(99, 'Dev Test Site', 'Test', 'This is not a real site', NULL, NULL, NULL, NULL);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(1, 'Delta Junction, AK', 'DeltaJunction', 'Remote, arctic, background, boreal forest, intercontinental transport, EPSCoR', 63.88112, -145.75136, 'America/Anchorage', -9);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(2, 'Cheeka Peak/ Makah', 'CheekaPeak', 'Marine background/inflow, smoke at times, tribal site', 48.29786, -124.62491, 'America/Los_Angeles', -8);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(3, 'Los Angeles-Pico Rivera', 'LosAngeles', 'Paired site 1: urban, anthropogenic, VCP, wildfires', 34.010278, -118.068611, 'America/Los_Angeles', -8);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(4, 'Rubidoux', 'Rubidoux', 'Paired site 2: urban, anthropogenic, aged OA, wildfires', 33.99958, -117.41601, 'America/Los_Angeles', -8);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(5, 'Joshua Tree', 'JoshuaTree', 'Paired site 3: aged OA, downwind of LA and Riverside', 34.06957, -116.38893, 'America/Los_Angeles', -8);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(6, 'Yellowstone NP 2', 'Yellowstone', 'Background site with wildfires, EPSCoR', 44.565217, -110.400996, 'America/Denver', -7);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(7, 'La Casa', 'LaCasa', 'Urban, wintertime pollution, oil and gas, wildfires, agriculture', 39.77949, -105.0491253, 'America/Denver', -7);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(8, 'Houston-UH West Liberty', 'Houston', 'Urban, petrochemical industry, maritime shipping', 30.0583, -94.9781, 'America/Chicago', -6);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(9, 'Lawrenceville', 'Lawrenceville', 'Urban, oil and gas, fracking, heavy industry', 40.46542, -79.960757, 'America/New_York', -5);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(10, 'Queens College 2', 'QueensCollege', 'Urban, coastal, VCP', 40.73614, -73.82153, 'America/New_York', -5);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(11, 'South DeKalb', 'SouthDeKalb', 'Paired site 1: urban, biogenic', 33.6878, -84.2905, 'America/New_York', -5);
INSERT INTO common.sites (site_number, site_name, site_code, description, latitude, longitude, timezone, gmt_offset) VALUES(12, 'Great Smoky Mountains NP - Look Rock', 'LookRock', 'Paired site 2: background, biogenic', 35.63348, -83.941606, 'America/New_York', -5);
